/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.ConsoleDAO;
import JDBC.ConnectionFactory;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javabeans.Console;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author danie
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameTela = new javax.swing.JInternalFrame();
        jLabeltitulo = new javax.swing.JLabel();
        jButtonSAir = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnumerodesérie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpreço = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtlançamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtvalorderevenda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtprévenda = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtvalordefornecedor = new javax.swing.JTextField();
        btnnovo = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        NW = new javax.swing.JCheckBox();
        XB = new javax.swing.JCheckBox();
        PS = new javax.swing.JCheckBox();
        Limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameTela.setBackground(new java.awt.Color(153, 255, 204));
        jInternalFrameTela.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jInternalFrameTela.setVisible(true);
        jInternalFrameTela.getContentPane().setLayout(null);

        jLabeltitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabeltitulo.setText("                          Cadastro de dados do Console");
        jInternalFrameTela.getContentPane().add(jLabeltitulo);
        jLabeltitulo.setBounds(90, 10, 450, 30);

        jButtonSAir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSAir.setText("Sair");
        jButtonSAir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSAirActionPerformed(evt);
            }
        });
        jInternalFrameTela.getContentPane().add(jButtonSAir);
        jButtonSAir.setBounds(10, 10, 90, 30);

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNome.setText("Nome");
        jInternalFrameTela.getContentPane().add(jLabelNome);
        jLabelNome.setBounds(20, 80, 60, 30);

        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        jInternalFrameTela.getContentPane().add(txtnome);
        txtnome.setBounds(80, 80, 510, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Numero de série");
        jInternalFrameTela.getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 130, 129, 22);

        txtnumerodesérie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumerodesérieActionPerformed(evt);
            }
        });
        jInternalFrameTela.getContentPane().add(txtnumerodesérie);
        txtnumerodesérie.setBounds(30, 160, 270, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Preço");
        jInternalFrameTela.getContentPane().add(jLabel4);
        jLabel4.setBounds(490, 130, 43, 22);

        txtpreço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreçoActionPerformed(evt);
            }
        });
        jInternalFrameTela.getContentPane().add(txtpreço);
        txtpreço.setBounds(380, 160, 270, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Lançamento");
        jInternalFrameTela.getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 200, 95, 22);
        jInternalFrameTela.getContentPane().add(txtlançamento);
        txtlançamento.setBounds(40, 240, 260, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Valor de Revenda");
        jInternalFrameTela.getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 200, 138, 22);
        jInternalFrameTela.getContentPane().add(txtvalorderevenda);
        txtvalorderevenda.setBounds(380, 240, 270, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Pré Venda");
        jInternalFrameTela.getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 290, 80, 22);
        jInternalFrameTela.getContentPane().add(txtprévenda);
        txtprévenda.setBounds(40, 320, 260, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Valor de Fornecedor");
        jInternalFrameTela.getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 290, 158, 22);
        jInternalFrameTela.getContentPane().add(txtvalordefornecedor);
        txtvalordefornecedor.setBounds(380, 320, 270, 30);

        btnnovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnnovo.setText("EXCLUIR");
        btnnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovoActionPerformed(evt);
            }
        });
        jInternalFrameTela.getContentPane().add(btnnovo);
        btnnovo.setBounds(190, 450, 120, 40);

        btnsalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsalvar.setText("SALVAR");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });
        jInternalFrameTela.getContentPane().add(btnsalvar);
        btnsalvar.setBounds(350, 450, 120, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("RELATÓRIO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrameTela.getContentPane().add(jButton2);
        jButton2.setBounds(510, 450, 120, 40);

        NW.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NW.setText("Nintendo");
        NW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NWActionPerformed(evt);
            }
        });
        jInternalFrameTela.getContentPane().add(NW);
        NW.setBounds(90, 370, 89, 25);

        XB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        XB.setText("Xbox");
        XB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XBActionPerformed(evt);
            }
        });
        jInternalFrameTela.getContentPane().add(XB);
        XB.setBounds(220, 370, 80, 25);

        PS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PS.setText("Playstation");
        PS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSActionPerformed(evt);
            }
        });
        jInternalFrameTela.getContentPane().add(PS);
        PS.setBounds(330, 370, 110, 25);

        Limpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        jInternalFrameTela.getContentPane().add(Limpar);
        Limpar.setBounds(50, 450, 110, 40);

        getContentPane().add(jInternalFrameTela);
        jInternalFrameTela.setBounds(0, 0, 700, 540);

        setBounds(0, 0, 717, 579);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumerodesérieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumerodesérieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumerodesérieActionPerformed

    private void txtpreçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreçoActionPerformed

    private void btnnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovoActionPerformed
        // TODO add your handling code here:

        try {
            //Registra JDBC driver
            Class.forName("com.mysql.jdbc.Driver");
 
            //Abrindo a conexão
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/jogos", "root", "");
 
            //Executa a query de exclusão
            java.sql.Statement st = conn.createStatement();
            st.executeUpdate("DELETE FROM tipoconsole WHERE cadastro ='" + this.btnnovo.getText() + "'");
            JOptionPane.showMessageDialog(rootPane, "Console excluído");
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }//Fim try
    }//GEN-LAST:event_btnnovoActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        try {
            // botao salvar
            //1 passo - guardar os dados da tela no obj console

            Console obj = new Console();

            obj.setNome(txtnome.getText());
            obj.setNumerodeserie(Integer.parseInt(txtnumerodesérie.getText()));
            obj.setPreco( Double.parseDouble(txtpreço.getText()));
            obj.setLancamento(Integer.parseInt(txtlançamento.getText()));
            obj.setValorderevenda( Double.parseDouble(txtvalorderevenda.getText()));
            obj.setPrevenda( Double.parseDouble(txtprévenda.getText()));
            obj.setValordefornecedor(Double.parseDouble(txtvalordefornecedor.getText()) );

             if(NW.isSelected()){
                obj.setConsole(NW.getText());
            }
             
              if(XB.isSelected()){
                obj.setConsole(XB.getText());
            }
              
               if(PS.isSelected()){
                obj.setConsole(PS.getText());
            }
            //2 passo - criar um obj do tipo consoleDAO

            ConsoleDAO dao = new ConsoleDAO();
            dao.cadastrarConsole(obj);

            JOptionPane.showConfirmDialog(null, "cadastro realizado com sucesso ");

        } catch (Exception erro) {
            JOptionPane.showConfirmDialog(null, "erro ao cadastrar" + erro);
        }
        

    }//GEN-LAST:event_btnsalvarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Connection conn = ConnectionFactory.conecta();

        String src = "C:\\Users\\danie\\Desktop\\ProgramaConsole\\MyReports\\Console.jasper";

        JasperPrint jaspertPrint = null;

        try {

            jaspertPrint = JasperFillManager.fillReport(src, null, conn);

        }catch (JRException ex) {
            System.out.println("Error: "+ex);
        }

        JasperViewer view = new JasperViewer(jaspertPrint,false);

        view.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NWActionPerformed
        // TODO add your handling code here:

        Console obj = new Console();
        obj.setNome(txtnome.getText());
        if(NW.isSelected()){
            obj.setNome(NW.getText());

        }
    }//GEN-LAST:event_NWActionPerformed

    private void XBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XBActionPerformed
        // TODO add your handling code here:
        Console obj = new Console();
        obj.setNome(txtnome.getText());
        if(XB.isSelected()){
            obj.setNome(XB.getText());

        }

    }//GEN-LAST:event_XBActionPerformed

    private void PSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSActionPerformed
        // TODO add your handling code here:

        Console obj = new Console();
        obj.setNome(txtnome.getText());
        if(PS.isSelected()){
            obj.setNome(PS.getText());

        }

    }//GEN-LAST:event_PSActionPerformed

    private void jButtonSAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSAirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSAirActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        // TODO add your handling code here:
        this.txtnome.setText("");
        this.txtlançamento.setText("");
        this.txtnumerodesérie.setText("");
        this.txtpreço.setText("");
        this.txtprévenda.setText("");
        this.txtvalordefornecedor.setText("");
        this.txtvalorderevenda.setText("");
        this.NW.setSelected(false);
        this.PS.setSelected(false);
        this.XB.setSelected(false);
    }//GEN-LAST:event_LimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpar;
    private javax.swing.JCheckBox NW;
    private javax.swing.JCheckBox PS;
    private javax.swing.JCheckBox XB;
    private javax.swing.JButton btnnovo;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonSAir;
    private javax.swing.JInternalFrame jInternalFrameTela;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabeltitulo;
    private javax.swing.JTextField txtlançamento;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnumerodesérie;
    private javax.swing.JTextField txtpreço;
    private javax.swing.JTextField txtprévenda;
    private javax.swing.JTextField txtvalordefornecedor;
    private javax.swing.JTextField txtvalorderevenda;
    // End of variables declaration//GEN-END:variables

    private void apagar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
}
